# Generated by Django 4.1.5 on 2023-03-10 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('da', '0002_tbllogistic_tcontract_tpickupaddress_tshiptoaddress_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='texphawb',
            name='exp_shipping_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='da.tbllogistic'),
        ),
    ]
