# Generated by Django 4.1.5 on 2023-03-10 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('da', '0004_alter_tbllogistic_exp_hawb_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'TBL_SHIPPING_DETAILS',
            },
        ),
        migrations.AlterField(
            model_name='texphawb',
            name='exp_shipping_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='da.tbllogistic'),
        ),
        migrations.CreateModel(
            name='Hawb',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('hawb', models.CharField(max_length=255)),
                ('shipping_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='da.shippingdetails')),
            ],
            options={
                'db_table': 'TBL_HAWB',
            },
        ),
    ]
