# Generated by Django 4.1.5 on 2023-03-10 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('da', '0005_shippingdetails_alter_texphawb_exp_shipping_id_hawb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='texphawb',
            name='exp_shipping_id',
        ),
        migrations.RemoveField(
            model_name='tbllogistic',
            name='exp_hawb_id',
        ),
        migrations.DeleteModel(
            name='Hawb',
        ),
        migrations.DeleteModel(
            name='ShippingDetails',
        ),
        migrations.DeleteModel(
            name='Texphawb',
        ),
    ]
