# Generated by Django 4.1.5 on 2023-03-31 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('da', '0006_remove_texphawb_exp_shipping_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TInvoiceType',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('type', models.CharField(db_column='TYPE', max_length=255)),
            ],
            options={
                'db_table': 'TINVOICETYPE',
            },
        ),
        migrations.CreateModel(
            name='TRegime',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('code', models.CharField(db_column='CODE', max_length=255)),
                ('is_import', models.BooleanField(db_column='IS_IMPORT')),
                ('description', models.CharField(db_column='DESCRIPTION', max_length=255)),
            ],
            options={
                'db_table': 'TREGIME',
            },
        ),
        migrations.CreateModel(
            name='TServiceProvider',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='NAME', max_length=255)),
            ],
            options={
                'db_table': 'TSERVICEPROVIDER',
            },
        ),
        migrations.CreateModel(
            name='TExpInvoiceShipping',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('shipping_id', models.CharField(db_column='SHIPPING_ID', max_length=255)),
                ('regime', models.ForeignKey(db_column='REGIME_ID', on_delete=django.db.models.deletion.PROTECT, to='da.tregime')),
            ],
            options={
                'db_table': 'TEXPINVOICE_SHIPPING',
            },
        ),
        migrations.CreateModel(
            name='TExpInvoice',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(db_column='INVOICE_NUMBER', max_length=255)),
                ('invoice_date', models.DateField(db_column='INVOICE_DATE')),
                ('amount', models.DecimalField(db_column='AMOUNT', decimal_places=2, max_digits=15)),
                ('pjf', models.CharField(db_column='PJF', max_length=255)),
                ('invoice_year', models.IntegerField(db_column='INVOICE_YEAR')),
                ('exp_shipping', models.ForeignKey(db_column='EXP_SHIPPING_ID', on_delete=django.db.models.deletion.PROTECT, to='da.texpinvoiceshipping')),
                ('invoice_type', models.ForeignKey(db_column='INVOICE_TYPE_ID', on_delete=django.db.models.deletion.PROTECT, to='da.tinvoicetype')),
                ('service_provider', models.ForeignKey(db_column='SERVICE_PROVIDER_ID', on_delete=django.db.models.deletion.PROTECT, to='da.tserviceprovider')),
            ],
            options={
                'db_table': 'TEXPINVOICE',
            },
        ),
        migrations.CreateModel(
            name='TblInvoice',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(db_column='INVOICE_NUMBER', max_length=255)),
                ('invoice_date', models.DateField(db_column='INVOICE_DATE')),
                ('invoice_amount', models.DecimalField(db_column='INVOICE_AMOUNT', decimal_places=2, max_digits=15)),
                ('pjf', models.CharField(db_column='PJF', max_length=255)),
                ('remarks', models.CharField(db_column='REMARKS', max_length=255)),
                ('invoice_year', models.IntegerField(db_column='INVOICE_YEAR')),
                ('invoice_type', models.ForeignKey(db_column='INVOICE_TYPE_ID', on_delete=django.db.models.deletion.PROTECT, to='da.tinvoicetype')),
                ('service_provider', models.ForeignKey(db_column='SERVICE_PROVIDER_ID', on_delete=django.db.models.deletion.PROTECT, to='da.tserviceprovider')),
            ],
            options={
                'db_table': 'TBL_INVOICE',
            },
        ),
        migrations.CreateModel(
            name='TblInvoiceShipping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice', models.ForeignKey(db_column='INVOICE_ID', on_delete=django.db.models.deletion.CASCADE, to='da.tblinvoice')),
                ('shipping', models.ForeignKey(db_column='SHIPPING_ID', on_delete=django.db.models.deletion.CASCADE, to='da.texpinvoiceshipping')),
            ],
            options={
                'db_table': 'TBL_INVOICE_SHIPPING',
                'unique_together': {('invoice', 'shipping')},
            },
        ),
    ]
