# Generated by Django 4.1.5 on 2023-03-31 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('da', '0007_tinvoicetype_tregime_tserviceprovider_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TBL_POSTCLEARANCE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CCD', models.CharField(max_length=255)),
                ('STAT_COST', models.DecimalField(decimal_places=2, max_digits=10)),
                ('PROCEDURES', models.CharField(max_length=255)),
                ('DATE_ISSUE', models.DateField()),
                ('DATE_SEND_ACCOUNT', models.DateField()),
                ('FACT_COST', models.DecimalField(decimal_places=2, max_digits=10)),
                ('VAT_TOTAL', models.DecimalField(decimal_places=2, max_digits=10)),
                ('DUTY_TOTAL', models.DecimalField(decimal_places=2, max_digits=10)),
                ('VAT_TOTAL_OFFSET', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='TBL_PRECLEARANCE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SHORT_DECLARATION_DATE', models.DateField()),
                ('SHIPPING_INVOICE', models.CharField(max_length=255)),
                ('DATE_SHIPPING_INVOICE', models.DateField()),
                ('DATE_SEND_BC', models.DateField()),
                ('REMARKS', models.TextField()),
                ('REGIME_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='da.tregime')),
            ],
        ),
        migrations.CreateModel(
            name='TCHARACTERDEAL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CODE', models.CharField(max_length=255)),
                ('DESCRIPTION', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TCURRENCY',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NUM', models.CharField(max_length=3)),
                ('CODE', models.CharField(max_length=3)),
                ('DESCRIPTION', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TCODE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CODE_TNBD', models.CharField(max_length=255)),
                ('DUTY', models.DecimalField(decimal_places=2, max_digits=10)),
                ('VAT', models.DecimalField(decimal_places=2, max_digits=10)),
                ('VAT_OFFSET', models.DecimalField(decimal_places=2, max_digits=10)),
                ('POSTCLEAR_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codes', to='da.tbl_postclearance')),
            ],
        ),
        migrations.CreateModel(
            name='TBL_PRECLEARANCE_SHIPPING',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PRECLEARANCE_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shippings', to='da.tbl_preclearance')),
            ],
        ),
        migrations.CreateModel(
            name='TBL_POSTCLEARANCE_PRECLEARANCE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CODE_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='da.tcode')),
                ('PRECLEARANCE_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='da.tbl_preclearance')),
            ],
        ),
        migrations.AddField(
            model_name='tbl_postclearance',
            name='CHARACTER_DEAL_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='da.tcharacterdeal'),
        ),
        migrations.AddField(
            model_name='tbl_postclearance',
            name='CURRENCY_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='da.tcurrency'),
        ),
        migrations.AddField(
            model_name='tbl_postclearance',
            name='REGIME_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='da.tregime'),
        ),
    ]
